## Abstract
Super shoes have been a recent phenomenon in the running community, with many top racers relying on them to boost their running economy. Many biological studies tackle this sensation, suggesting super shoes improve running efficiency. However, is there statistical evidence that these shoes are making a difference in recent marathon performances? In addition, can this recent phenomenon be generalized to observe significant changes in the trend of marathon records over the course of the last few decades? Through the use of Extreme Value Theory, Bayesian statistics, and multiple changepoint models, these questions are tackled in a two-part study. The first part analyzes the historical trends of marathon records, detecting no single event that has changed the trajectory of the fastest marathon times in a given year. The second part analyzes the recent impact of super shoes on marathon performances, establishing a correlation between the introduction of super shoes in 2017 and a significant difference in performance trends.
---
<br>
To view my senior honors thesis, you may either click on the following link or view the embedded pdf below:

- [Changepoint Analysis on Marathon and Half Marathon Data; An Insight on Annual Record Trends and Recent Major Marathon Performances](projects/Thesis.pdf)

<div style="position: absolute; left: 50%; transform: translateX(-50%); width: 90vw; margin-top: 132px;">
  <iframe src="projects/Thesis.pdf#zoom=page-width" style="width: 100%; height: 90vh; border: none;"></iframe>
</div>
