## Abstract
The spread of infectious diseases such as influenza is influenced by various factors, one
of the most significant being the efficacy of a vaccine. This is particularly relevant when
comparing rural and urban populations, where access to vaccination can differ substantially. We
aim to explore this phenomenon in greater depth by utilizing population data while toggling
many key parameters in our model such as: vaccination rate ($\theta$), vaccination efficacy ($\epsilon$), andθ ϵ
recovery rate ($\alpha$). The parameters will be modeled in a discrete Susceptible, Vaccinated, Infected,α
Recovered (SVIR) model to assess their interactions with one another in a disease simulation. By
viewing the changes in the proportion of initial susceptibles ($S_0$) that have not been infected ($q$), we can deduce how these factors interact to influence the spread of influenza. In addition to the
basic SVIR model, we want to consider two strains of influenza, because typically influenza
spreads many strains at a given time. By incorporating this variation, we aim to understand how
slight differences in the virus, in conjunction with varying vaccine efficacies, can influence the
spread of the disease across populations.

---

<div style="position: absolute; left: 50%; transform: translateX(-50%); width: 90vw; margin-top: 132px;">
  <iframe src="projects/poster1.pdf#zoom=page-width" style="width: 100%; height: 90vh; border: none;"></iframe>
</div>
